### ISSUE TITLE
The GUI wallet Transaction DETAIL popup screen has a serious defect.

### ISSUE THREAD

**Issue by robotsoutofcontrol** [jojapoppa/fedoragold-wallet-electron#4] opened 2019-03-15 00:34 UTC
When displaying transaction detail popup (for SEND transactions), the "Address" field shows the sender's original address, not the destination address.

When viewing transaction detail popup for RECEIVE transactions, it displays your own (receiver's) address. Should it display the senders?

**Comment by jojapoppa** [comment] 2019-04-27 03:05
not a bug... it's a privacy coin... if you want to make a trackable transaction you need to assign it a payment id.

**Comment by jojapoppa** [comment] 2019-04-27 16:57
not a bug... with privacy coins if you want to track it you need to create a payment ID...

**Closed** 2019-04-27 16:56 UTC
